spring:
    datasource:
        url: jdbc:mysql://tecreations.ca:3306/rentCloudDB?createDatabaseIfNotExist=true
        username: rentcloud
        password: rentCloudPass69$$$
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
