management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 9898
    
spring:
    datasource:
        url: jdbc:mysql://tecreations.ca:3306/rentCloudDB?createDatabaseIfNotExist=true
        username: rentcloud
        password: rentCloudPass69$$$
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
        show-sql: true
    hikari:
        keepAliveTime: 28800
